### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/photoswipe#1]
Es gibt offenbar noch kein Release im Installer. Wollen wir eins machen?

**Comment by gseilheimer** [comment]
Gern. 
(Es ist viel Zeit vergangen und ich muss mir den Code erst ansehen warum ich es nicht im Installer habe...)

**Comment by webregie** [comment]
Ja schade, dass es nicht bereit ist. Habe es in der aktuellen 5.5.1 installiert und da fehlt ein bisschen was... Es ist doch so eine tolle Lightbox!

**Comment by gseilheimer** [comment]
Ja, stimmt. Es fehlt nicht mehr viel. 
Ab Mitte Februar besteht eine realistische Change das AddOn fertigzustellen. Bis dahin über die direkte Einbindung im entsprechenden Theme-Projekt-Ordner.

**Comment by webregie** [comment]
Das ging schnell. Ich schaue mal, wie ich das machen kann. Ich benötigte eigentlich nur deine Herangehensweise. Es ist ja an einigen Ecken speziell. Gut gemacht soweit!

**Comment by gseilheimer** [comment]
Einfach in SLACK anschreiben, dann klären wir die Details.
